layout/mstab.lua
I changed how padding/height works in tabbars. Basically, I added a padding option to adjust the space between the tabbar and client.
(Clients also change size to count for padding)
* 0 padding, top
* 20 padding, top
* 0 padding, bottom
* 20 padding, bottom
=> Tabbar Padding Option

signal/playerctl.lua
This PR should deal with the leaks as described in #24. This seems to be a problem with the GC and the `awful.spawn.easy_async` commands, as said [here](https://github.com/awesomeWM/awesome/issues/1490).
=> Deal with playerctl signal module leaks

helpers/client.lua, module/tabbed.lua, module/window_swallowing.lua
There has been more or less the same syncing function in the tabbed and the window_swallowing module so I moved them into the client helper functions. Since these modules are a little more complex, it would be cool if someone can take a look before I merge.
=> moved sync functions to helpers

bling-scm-1.rockspec, bling-scm-2.rockspec
Because AwesomeWM is not distributed through LuaRocks, having a dependency on awesome results in the rock being uninstallable.
=> Remove awesome dependency

docs/_sidebar.md, docs/theme.md, docs/widgets/tag_preview.md, init.lua, theme-var-template.lua, widget/init.lua, widget/tag_preview.lua
Default theme ->
My theme ->
(They look different because my gaps were at different values)
=> Add tag preview widget

README.md, docs/_sidebar.md, docs/module/scratch.md, helpers/client.lua, module/init.lua, module/scratchpad.lua, module/window_swallowing.lua
A scratchpad module as long proposed in #19. 
Try it out, by initalizing it with something along those lines:
```lua
local scratchpad = require("bling.module.scratchpad")
local term_scratch = scratchpad:new { 
command = "wezterm start --class spad", -- how to spawn the scratchpad
rule = { instance = "spad" }, -- what awesomeWM rule the scratchpad matches
sticky = true, -- whether the scratchpad should be sticky
autoclose = true, -- whether it should hide itself when losing focus
floating = true, -- whether it should be floating
geometry={x=360, y=90, height=900, width=1200}, -- the geometry in a floating state
reapply = false, -- whether all those properties should be reapplied on every new opening of the scratchpad
}
```
Then you should be able to `toggle` the scratchpad by doing (same …
=> Scratchpad feature

docs/module/scratch.md, helpers/client.lua, module/scratchpad.lua, widget/tag_preview.lua
This PR will bring animations to scratchpad using `awestore`. It allows the user to pass in a store table from `awestore` to have the scratchpads subscribe x and y changes from it. With this method, users will not have to have `awestore` installed to use `bling` without animations.
Using animations for both x and y is as easy as this:
```lua
local anim_y = awestore.tweened(1100, {
duration = 300,
easing = awestore.easing.cubic_in_out
})
local anim_x = awestore.tweened(1920, {
duration = 300,
easing = awestore.easing.cubic_in_out
})
local discord_scratch = bling.module.scratchpad:new{
command = "discord",
rule = {instance = "discord"},
sticky = false,
autoclose = false,
floating = true,
geometry = {x = 460, y = 90, height = 900, width = 1000},
reapply = true,
dont_focus_before_close = …
```
=> Awestore support for scratchpads

docs/signals/pctl.md, docs/theme.md, signal/playerctl.lua, theme-var-template.lua
This PR is a rewrite of the playerctl signals backend using the [playerctl](https://github.com/altdesktop/playerctl) library through [lgi](https://github.com/pavouk/lgi/) bindings. It does not introduce any breaking changes to the signals themselves and should be fully compatible with code currently using these signals. That said here are some notable changes:
Configuration options `player`, `ignore`, and `update_on_activity` have been added in addition to the the `interval` that is already present. Here is a quick summary of what they do
* `player`: Either a string (in the case of a single name) or table of strings containing names of players this backend should provide signals for. It works the same way as the `--player` option of the `playerctl` command line utility. Players listed …
=> Playerctl signals backend rewritten with playerctl library

module/tabbed.lua
With this patch you may:
- from focused single window pick another single wimdow
- from focused single window pick a tabgroup window
- from focused tabgroup window pick a single window
All ways of actions will work exactly the same: single window will be added to a new one or either already existing tabgroup window.
=> [tabbar] change PID to windowID + add for both directions of pick/focus 

signal/playerctl/playerctl_lib.lua
Not sure why I made some of these functions global but they shouldn't be.
=> Cleanup of some global functions in playerctl lib backend

widget/tag_preview.lua
Because I find X, Y stinky
and it allows me to do something like this
```lua
bling.widget.tag_preview.enable {
show_client_content = false,
scale = 0.25,
-- CHANGE
placement_fn = function(c) awful.placement.top_right(c, {margins={top=30,right=50}}) end,
honor_padding = true,
honor_workarea = true
}
```
Which I find pretty neat
=> adds placement function support to tag preview

module/scratchpad.lua
- Add an option to disable the client floating state when closing the scratchpad
- Fix an issue where a scratchpad can't be toggled with dont_focus_before_close unless doing so from the first tag
=> Scratchpad improvments

docs/_sidebar.md, docs/theme.md, docs/widgets/task_preview.md, theme-var-template.lua, widget/init.lua, widget/task_preview.lua
This is the thingy that William Fence's OS does. It has the same behavior as the tag preview widget, when hovering over a client item in the task list, this widget should appear.
Basic (mine) configuration:
```lua
bling.widget.task_preview.enable {
placement_fn = function(c)
awful.placement.bottom(c, {
margins = {
bottom = beautiful.wibar_height + beautiful.useless_gap / 2
}
})
end
}
```
This also reuses the sweet placement stuff from @undefinedDarkness :rocket:
=> Task Preview Widget

widget/tabbar/modern.lua
I remember that in previous versions in Bling it already had buttons for the tabbars as I show in the image. This pull request is to return if possible those buttons for the tabbars of the windows.
I hope they can return them because even in the documentation for this it tells you that you can change the color of the buttons, but since these do not exist, this can be confusing (well that was my case as a novice AwesomeWM user)
=> Adding Close, Minimize and Float buttons in tabbar (again)

docs/module/tabbed.md, module/tabbed.lua
This allows you to much more easily integrate bling into your actual titlebar and no longer have 2 titlebars taking up space, it also allows you to represent bling tabs in your bar but that is quite a chore
Example code for titlebar
```lua
local tabbed_icons = wibox.widget({
layout = wibox.layout.fixed.horizontal,
spacing = dpi(4),
})
awesome.connect_signal("bling::tabbed::update", function(group)
local focused = group.clients[group.focused_idx]
if require("misc.libs.stdlib").contains(group.clients, c) then
tabbed_icons:reset()
for idx, _c in ipairs(group.clients) do
tabbed_icons:add(wibox.widget({
{
{
{
client = _c,
widget = awful.widget.clienticon,
forced_width = 20,
forced_height = 20,
},
widget = wibox.container.margin,
margins = dpi(4),
},
widget = wibox.container.background,
bg = _c …
```
=> Tabbed: added a signal and a way to disable the titlebar

docs/module/tabbed.md, helpers/client.lua, module/tabbed.lua
Instead of picking the next tabbed client with the cursor or with dmenu, one should now be able to pick it through directions. ie `bling.module.tabbed.pick_by_direction("left")` should merge with the client to the left of the currently focused one. Someone please test it before I merge.
=> Tab pick by direction

widget/tag_preview.lua
`tag_preview` widget was not showing any border.
=> Fixed tag_preview: shape_border_color and shape_border_width

signal/playerctl/playerctl_lib.lua
* Only pass artUrl to the signal if it's not empty
* Fix for double signals:
What I've found while using dbus-monitor is that playerctl sends a bunch of messages whenever media is changed, with the first one always having the artUrl empty.
If the media does have an artUrl, the second and next messages will contain the artUrl resulting in artUrl ~= last_artUrl becoming true and triggering another signal
The hacky method in the commit will only trigger a new signal if artUrl is not empty, or on the second message sent (as some media don't provide any art)
=> Fixes for the playerctl_lib signals

docs/module/scratch.md, module/scratchpad.lua
This PR will add awesome-style signals to scratchpad instances. Currently there are three: `turn_on`, `turn_off` and `launch`. I'm not completly set on the names of the signals and whether or not to pass them arguments. Also `turn_on` currently misfires when the scratchpad gains focus through the `turn_on` function.
=> scratchpad signals

signal/playerctl/playerctl_lib.lua
I encountered some errors when player wasn't nil (i.e firefox was running but no media was playing) so this fixes that
=> Fix an error with playerctl

signal/playerctl/playerctl_lib.lua
I started having issues again (I think it's a result of 74f522cc8823eaffa4e11b6635951f9e196462e3) with YouTube and playerctl notifications, so this should re-fix it and in a less hacky way by implementing the suggestion @HumblePresent made at #77.
The 0.3 delay seems to do the job to stop double notifications (less is a hit-and-miss), but more testing is needed
A side effect I found is that when switching songs fast enough, a signal will be emitted only for the last song.  I personally think it's a good change, as I'd rather not have 10 different notifications when I'm only trying to skip some songs
=> Add playerctl lib signals debounce as a better workaround for #77

.editorconfig, README.md
Every editor have built in support or simple extension for this `.editorconfig`, this little file automatically configure your editor for bling code style and re-configure to regular settings when you exit `bling` folder.
Also contributors img was removed from readme since you can see list of contributors on the right side.
=> Add .editorconfig

docs/_sidebar.md, docs/widgets/window_switcher.md, theme-var-template.lua
Adding documentation (`theme-var-template` + normal docs) for the new window switcher widget.
@Kasper24 Did I catch all options and theme variables and label them correctly? (also maybe someone can take a look at my english :thumbsup:)
I should have only left the three "mouse bindings" (`scroll_previous_key`, `scroll_next_key`, `select_client_key`) options out for now. I found it weird to document those as it's probably more confusing to explain than it is useful since there isn't really another sane option to bind those to then the defaults I think.
=> Window switcher docs

docs/widgets/tag_preview.md, widget/tag_preview.lua
The tag preview widgets can have a wallpaper background.
Sample:
```lua
bling.widget.tag_preview.enable {
show_client_content = false,
scale = 0.15,
honor_padding = true,
honor_workarea = false,
background_image = wibox.widget  {
image = beautiful.wallpaper,
horizontal_fit_policy = "fit",
vertical_fit_policy   = "fit",
widget = wibox.widget.imagebox
}
}
```
=> Added new feature for tag_preview widget

module/icon_theme.lua
This adds an easy way to retrive icons from the currently selected theme, mainly to be used for the tag/task preview and the window switcher widget. 
It does have a dependency on gtk though.
=> Add a new 'icon-theme' module

widget/tag_preview.lua, widget/task_preview.lua
@JavaCafe01 
Some other issues:
1. I think these widgets should be turned into proper objects, with methods like :show() :hide() and :toggle() instead of the current signals. 
2. When there isn't an available client.content to preview, the tag preview displays a black background with the client icon in the cener. The task preview before this PR would always show the client.content, so there wasn't a need for that - but maybe we should at now do it here too?
3. The task preview height differes between clients. I think it has to be with the title not being limited in size?
4.  What about using #129 to the get the icons for the running clients? It will retrive the icon for the running client from the currently system selected icon theme, or whatever theme was passed to the constructor
=> Fix some issue with the client preview for the tag and task preview widgets

layout/centered.lua, layout/deck.lua, layout/equalarea.lua, layout/horizontal.lua, layout/init.lua, layout/mstab.lua, layout/vertical.lua
This PR moves the responsibility for getting the layout icons from the layouts itself to the `layout/init.lua` file as the code was just repeating itself anyway. Instead of searching in the config directory only, it now searches in all paths that are mentioned in `package.path` (because when bling is loaded successfully, the icons will obviously be in one of those paths too). This should fix #136. 
It also makes it possible to require layouts directly (ie `awful.layout.layouts { require("bling.layout.centered") }`)
=> Unify the layout icon path search and search in all `package.path` paths

module/scratchpad.lua
Fixes #146 for me. I am pretty new to the codebase and could be missing the intention of this area of the code.
=> Fix handling of signals in scratchpad when client is nil

AUTHORS.md, docs/module/swal.md, module/window_swallowing.lua
This is an incremental improvement of the swallowing module, so far what has been done:
* Changed the flags for the pstree command so it is a single line with all ancestors.
* Removed usage of sed, grep and tr so the iopopen call should be faster.
* Find and match of parent pid in the ancestors string is done in lua so should be faster.
* Rework the don't swallow filter and add table for clients that cannot swallow their parent.
What i still plan to do:
* ~~Rework the don't swallow filter and add table for clients that cannot swallow their parent.~~ done
* ~~Add persistent properties so parent clients can be restored after awesome restarts~~ can't decide on the better way to implement this so won't do it in this PR
altho i still have those plans the changes could be added to a later PR, …
=> Improved swallowing

docs/module/wall.md, module/wallpaper.lua
This PR adds support to the wallpaper module for multiple screens. It introduces the following changes -
1. Calling `setup` multiple times with different `screen` arguments works correctly
2. A new `screens` argument to the setup function, which allows setup of multiple screens by passing a table of screens. Currently only supports the simple and random pickers
=> [feat] Add support to wallpaper module for multiple screens

docs/home.md, docs/index.html
This pull request simply updates the repository urls in the documentation from `Nooo37/bling` to `BlingCorp/bling` in order to reflect the repository being moved to an organization.
=> Update repository urls in docs

module/flash_focus.lua
This small change simply prevents a client from flashing when only 1 client is there in a tag. The point of flashfocus is to tell which client is currently focused and flashing a lonely client seems redundant.
Some edge cases for this might include the client being in multiple tags or if the current tag has hidden clients, I'm a beginner with lua so I have not been able to test out these edge cases. Feedback is appreciated.
=> Prevent flashing client when only one is present

layout/init.lua
By putting the creation of a beautiful.layout variable into an if statement that checks if the variable doesn't exist already, the user is given the ability to change the layout icon inside their own theme.lua file.
=> Made layout icons changeable via theme.lua file

module/flash_focus.lua
The flash focus module calls a client's `:raise()`-method. However, since flash focus will only trigger when a window is focused by other means (that is, either manually by clicking a client or with focus-on-hover), there is really no reason for flash_focus to force-raise a client. By default, awesome explicitly sets the `raise` property to `false`, because it is more annoying than anything else (as can be seen in the videos at the bottom).
```lua
-- snippet taken from right at the very bottom of the default rc.lua
client.connect_signal("mouse::enter", function(c)
c:activate { context = "mouse_enter", raise = false }
end)
```
In addition, since the module is called "flash focus", not "flash raise", the current behavior is likely to be unexpected by a user.
---
Here are two videos showing …
=> Remove the unnecessary c:raise() call in flash_focus

module/tabbed.lua
Simple fix for the `tabbar_disable` theme variable not actually disabling the tabbar and overwriting the current titlebar.
=> tabbar: Fix tabbar_disable theme variable

docs/_sidebar.md, docs/widgets/app_launcher.md, widget/app_launcher/init.lua
Refer to #130 
I was actually trying to implement something exactly like this myself without knowing it already existed.  Hopefully adding the docs will help someone else find it on the bling website.
Couple things in this documentation.
1) I wasn't sure the proper way to give a description of every option, some I left blank because I don't understand what the options do.  (save_history, the `commands` options, and the rubato option)
2) I noticed a typo on the `shrink_width` option, but I didn't want to fix it without running it by your team first.  The correct move would be to rename from `shirnk_width` to `shrink_width` but I don't know the downstream effects or how you normally disseminate breaking changes like that, so I left it as `shirnk_width` and documented it as such.  Should I …
=> add app_launcher docs and basic options descriptions

docs/widgets/app_launcher.md, widget/app_launcher/init.lua
This PR adds `border_color` and `border_width` options to allow the `awful.popup` borders to be configured in app_launcher.
Also fixes a bug where `app_name_normal_color` was not applied when app entries were initially created and would only apply after `unselect_app` was called.
=> Add popup border config in app_launcher

widget/tabbar/default.lua, widget/tabbar/modern.lua
=> escape < and > in titlebars for tab widgets

layout/centered.lua
Yes, there's the master_width_policy, but it's a prop you set per tag rather than per layout, and for me personally, and I'd guess others it only makes sense to have it set to 'master_width_factor' for the centered layout, and I don't want that option for my other layouts, especially when using an ultrawide. Making it a beautiful variable is also possible, but I thought this way is more consistent
Here's an example from my config on how I'm using it
```LUA
awful.screen.connect_for_each_screen(function(s)
for i = 1, 8, 1  do
awful.tag.add(i, {
layout = awful.layout.layouts[1],
centered_layout_master_fill_policy = "master_width_factor",
screen = s,
selected = i == 1 and true or false,
})
end
end)
```
=> Centered layout for ultrawide screen

signal/playerctl/playerctl_lib.lua
Here are two minor bug fixes:
1. `get_player_of_name` - `name` property doesn't exist
2. `ret.update_on_activity` is always true (unfortunately boolean can't be used with multiple and/or for this)
=> Playerctl lib minor bug fixes

widget/window_switcher.lua
removed the get_num_clients function from window_switcher widget which returned the total number of clients on the selected tag and replaced it with the one line "#awful.screen.focused().selected_tag:clients()" which also returns the total number of clients on the selected tag to reduce the complexity of the code.
=> Replaced get_num_clients functions with one liner

widget/tabbar/modern.lua
Using `tabbed` module with `modern` style, if the title of the currently focused client is too long, the minimize-floating-close buttons are not displayed, as the following screenshot shows:
This work changes the layout so that the placement of the icon and the buttons take precedence over the placement of the title textbox. This way, the three elements are displayed correctly and the title is truncated as much as needed:
Moreover, as the screenshot shows, an extra margin has been added between the client icon and the title to prevent them to be stuck to each other.
=> Improve tabbar's layout with modern style

layout/deck.lua
On **deck layout** use currently unused master window factor to calculate **window offset**.
Previously this factor was hardcoded to `0.1`.
https://github.com/BlingCorp/bling/assets/61242172/3e851b1c-a0b0-4263-8145-2a285554c062
=> feat: Deck layout ability to adjust window size

docs/widgets/app_launcher.md, widget/app_launcher/init.lua
Just simply allows you to define the layout of the app name to allow it to be vertical with the icon (by default) or horizontal with the icon.
Visual example:
=> Feature: App Launcher layout
