README.md, layout/mstab.lua, module/helpers.lua, module/tabbed.lua, widget/tabbar/modern.lua
=> New Tabbar Theme

widget/tabbar/modern.lua
=> Client Icon on every tab

widget/tabbar/modern.lua
=> Added other titlebar buttons

README.md, module/tabbed.lua, widget/tabbar/modern.lua
* Buttons in tabs are darker on hover
* Switched `io.popen` to `awful.spawn`
* Tabs have sexy reverse corners on the bottom!
=> Tabbed Bar Feature Update

docs/index.html
path to image doesn't work, so we need to change it link to get it as preview image in embed
=> fix banner in embed

docs/_sidebar.md, docs/home.md, docs/javacafe.css, docs/layouts/layout.md, docs/module/flash.md, docs/module/scratch.md, docs/module/tabbed.md, docs/module/twall.md, docs/signals/pctl.md, docs/theme.md
Hello, just removed trailing spaces in docs, added scrollbar theme, themed markdown table and added better contrast for codeblocks 
Scrollbar was tested only in google chrome, I'm not sure if it's visible in firefox and other browsers.
=> Better CSS in docs

module/tabbed.lua
=> Fixed issues with the tabbed module

docs/widgets/task_preview.md
=> fix 2 letters in task_preview documentation

docs/widgets/task_preview.md, widget/task_preview.lua
tis a draft, documentation example needs to be tweaked, I just copy pasted the old code,
I dont remember why I changed it to use popups ..., smth to do with image size and looking bad and shadows
^^ might be worth getting rid of that idk
=> Task preview: more flexible layout control

helpers/client.lua, module/scratchpad.lua
=> More scratchpad fixes

module/tabbed.lua, theme-var-template.lua, widget/tabbar/boxes.lua, widget/tabbar/default.lua, widget/tabbar/modern.lua, widget/tabbar/pure.lua
Aims to add the theme variables as described in #112 
Would be cool if someone can try it out before merging
=> add tabbar_{fg,bg}_inactive theme var

widget/app_launcher.lua, widget/init.lua
How to use:
```LUA
local app_launcher = require("bling").widget.app_launcher()
app_launcher:toggle()
```
=> App launcher ala rofi widget

widget/tag_preview.lua
Mainly for applications like st that dont set a window icon by default.
I remember it working for me, can someone else test it?
=> [1/3] make tag preview fallback to a awesomewm icon

module/scratchpad.lua
This makes things easier and cleaner to understand. It also fixes a new issues that arose from a new rubato change
=> Scratchpad stop un and re subscribing

docs/layouts/layout.md, docs/theme.md, layout/mstab.lua, theme-var-template.lua
=> feat: allow disabling tabbar in mstab layout

docs/signals/pctl.md
@Kasper24 Can you confirm if everything is right?
=> Update Docs for the new Playerctl PR

layout/centered.lua
The centered layout currently ignores the `master_fill_policy`, turning the master area full-size even if the policy is set to `master_width_factor`.
Additionally, when you have multiple masters, the fallback layout for the single slave case, `awful.layout.suit.tile.right`, arranges them top to bottom, while the rest of this layout arranges them bottom to top.  
This means, if you have multiple masters and add the first slave, or close the second to last, the masters suddenly switch their order, which is surprising and somewhat annoying.
I skip handling the special cases for 0 and 1 slaves if the `master_fill_policy` is set to not expand masters beyond the `master_width_factor`. This means that the regular logic of the layout comes to work, leaving one or both slave areas empty if they …
=> Honor master_fill_policy in 'centered' layout

layout/mstab.lua
Seems to be what works for #163
=> Fix layout/mstab adjust_visibility

docs/widgets/window_switcher.md, widget/window_switcher.lua
Made the cycleClientsByIdx and filterClients configurable
Also made sure that the widget is always drawn on the focused screen
=> Made some function for window_switcher widget configurable

docs/home.md, docs/layouts/layout.md, docs/module/scratch.md, docs/module/tabbed.md, docs/module/wall.md, docs/widgets/app_launcher.md, docs/widgets/tabbed_misc.md, docs/widgets/task_preview.md
Some small changes to clean up the readability of the docs. Currently intend to make more edits over time.
=> Clean up docs grammar and consistency

docs/home.md, docs/layouts/layout.md, docs/module/flash.md, docs/module/scratch.md, docs/module/swal.md, docs/module/tabbed.md, docs/module/twall.md, docs/module/wall.md, docs/signals/pctl.md, docs/widgets/app_launcher.md, docs/widgets/tabbed_misc.md, docs/widgets/tag_preview.md, docs/widgets/task_preview.md, docs/widgets/window_switcher.md
Some more readability edits. Most errors were fixed, some wordings were changed. As far as I'm aware, no information has been lost in changes.
=> Readability edits for docs

bling-dev-2.rockspec
I'd like to use bling on nix but noticed a couple of files that were missing.
=> add app_launcher and bump version
